name: Deploy backend to Scaleway

on:
  push:
    branches:
      - main
    paths:
      - apps/frontend/**
      - .github/workflows/deploy-frontend.yaml

jobs:
  deploy-frontend:
    name: ðŸŽ¨ Deploy Static Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.24.0

      - name: Build Frontend
        working-directory: ./apps/frontend
        env:
          PUBLIC_CHATBOT_API_URL: https://nuitdelinfo2025jb7kukab-container-angry-sinoussi.functions.fnc.fr-par.scw.cloud/chat
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Upload to Scaleway Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.SCW_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_REGION: 'fr-par'
          AWS_S3_ENDPOINT: https://s3.fr-par.scw.cloud
          SOURCE_DIR: './apps/frontend/dist'
